version: '3.8'

services:
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - "5455:5432"
    volumes:
      - ./volumes/inventory-db:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - "5456:5432"
    volumes:
      - ./volumes/order-db:/var/lib/postgresql/data
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge