spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 9000
app:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5455/${POSTGRES_DATABASE_NAME:postgres}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASS:mypassword}
